global using Microsoft.EntityFrameworkCore;
global using NewListWizard.Models;
global using System.Text;
global using System.Security.Cryptography;
global using NewListWizard.Services;
global using System.ComponentModel.DataAnnotations;
global using System.Net.Mail;
global using System.Text.Json;
global using NewListWizard.CustomSessions;